#!/usr/bin/env python3
"""
Train a grass-density classifier from TOF feature JSONL files.

Input format:
- each line is JSON generated by tof_grass_density_features.py
- requires key: label

Example:
    python python_scripts/tof_grass_density_train.py \
    --inputs output/tof_features_sparse.jsonl output/tof_features_medium.jsonl output/tof_features_dense.jsonl \
    --model-out output/tof_grass_density_model.pkl
"""

from __future__ import annotations

import argparse
import json
import pickle
import random
from pathlib import Path
from typing import Any

try:
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
except ModuleNotFoundError as exc:
    print("Missing dependency: scikit-learn. Install with: python -m pip install scikit-learn")
    raise SystemExit(1) from exc


DEFAULT_FEATURES = [
    "valid_ratio",
    "dist_mean_mm",
    "dist_std_mm",
    "dist_p10_mm",
    "dist_p50_mm",
    "dist_p90_mm",
    "near_ratio_100mm",
    "near_ratio_200mm",
    "near_ratio_300mm",
    "center_edge_diff_mm",
    "roughness_mm",
    "avg_signal",
    "avg_ambient",
    "w_valid_ratio_mean",
    "w_valid_ratio_std",
    "w_dist_mean_mm_mean",
    "w_dist_mean_mm_std",
    "w_roughness_mm_mean",
    "w_roughness_mm_std",
]


def _to_float(value: Any) -> float:
    if value is None:
        return -1.0
    try:
        return float(value)
    except (TypeError, ValueError):
        return -1.0


def _read_jsonl(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open("r", encoding="utf-8") as rf:
        for line in rf:
            text = line.strip()
            if not text:
                continue
            try:
                obj = json.loads(text)
            except json.JSONDecodeError:
                continue
            if isinstance(obj, dict):
                rows.append(obj)
    return rows


def _split_indices(n: int, test_ratio: float, seed: int) -> tuple[list[int], list[int]]:
    idx = list(range(n))
    random.Random(seed).shuffle(idx)
    test_n = max(1, int(n * test_ratio))
    test_idx = idx[:test_n]
    train_idx = idx[test_n:]
    if not train_idx:
        train_idx = test_idx
    return train_idx, test_idx


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--inputs", nargs="+", required=True, help="Feature JSONL files")
    parser.add_argument("--model-out", default="output/tof_grass_density_model.pkl", help="Output model path")
    parser.add_argument("--test-ratio", type=float, default=0.2, help="Test split ratio")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    args = parser.parse_args()

    rows: list[dict] = []
    for raw in args.inputs:
        path = Path(raw)
        rows.extend(_read_jsonl(path))

    labeled = [r for r in rows if isinstance(r.get("label"), str) and r.get("label")]
    if len(labeled) < 20:
        raise SystemExit("Not enough labeled rows. Need at least 20 rows with non-empty label.")

    X: list[list[float]] = []
    y: list[str] = []
    for r in labeled:
        feat = [_to_float(r.get(name)) for name in DEFAULT_FEATURES]
        X.append(feat)
        y.append(str(r["label"]))

    train_idx, test_idx = _split_indices(len(X), args.test_ratio, args.seed)

    X_train = [X[i] for i in train_idx]
    y_train = [y[i] for i in train_idx]
    X_test = [X[i] for i in test_idx]
    y_test = [y[i] for i in test_idx]

    clf = RandomForestClassifier(
        n_estimators=300,
        max_depth=10,
        min_samples_leaf=3,
        random_state=args.seed,
        n_jobs=-1,
    )
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    labels = sorted(set(y))
    cm = confusion_matrix(y_test, y_pred, labels=labels)
    report = classification_report(y_test, y_pred, labels=labels, zero_division=0)

    print(f"rows_total={len(X)} rows_train={len(X_train)} rows_test={len(X_test)}")
    print(f"accuracy={acc:.4f}")
    print("labels=", labels)
    print("confusion_matrix=")
    print(cm)
    print("classification_report=")
    print(report)

    model_out = Path(args.model_out)
    model_out.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "model": clf,
        "feature_names": DEFAULT_FEATURES,
        "labels": labels,
        "seed": args.seed,
    }
    with model_out.open("wb") as wf:
        pickle.dump(payload, wf)

    print(f"model_saved={model_out}")


if __name__ == "__main__":
    main()
