#!/usr/bin/env python3
"""
Extract grass-density oriented features from TOF JSONL.

Input format:
- each line is JSON generated by tof_usart6_receiver.py
- requires key: frame

Example:
    python python_scripts/tof_grass_density_features.py \
    --in output/tof_frames.jsonl \
    --out output/tof_grass_features.jsonl \
    --window-size 15 \
    --label dense
"""

from __future__ import annotations

import argparse
import json
import math
from collections import deque
from pathlib import Path
from statistics import fmean, median
from typing import Iterable


def _percentile(sorted_values: list[float], p: float) -> float:
    if not sorted_values:
        return -1.0
    if p <= 0:
        return sorted_values[0]
    if p >= 100:
        return sorted_values[-1]

    rank = (len(sorted_values) - 1) * (p / 100.0)
    low = int(math.floor(rank))
    high = int(math.ceil(rank))
    if low == high:
        return sorted_values[low]
    weight = rank - low
    return sorted_values[low] * (1.0 - weight) + sorted_values[high] * weight


def _std(values: list[float], mean_value: float) -> float:
    if not values:
        return -1.0
    return math.sqrt(sum((v - mean_value) ** 2 for v in values) / len(values))


def _safe_mean(values: list[float]) -> float:
    return fmean(values) if values else -1.0


def _as_square_side(resolution: int) -> int:
    side = math.isqrt(resolution)
    return side if side * side == resolution else 0


def _center_edge_stats(dist: list[int], valid: list[int], side: int) -> tuple[float, float, float]:
    if side == 0:
        return -1.0, -1.0, -1.0

    center_idx: list[int] = []
    edge_idx: list[int] = []

    for r in range(side):
        for c in range(side):
            idx = r * side + c
            if r == 0 or c == 0 or r == side - 1 or c == side - 1:
                edge_idx.append(idx)
            else:
                center_idx.append(idx)

    center_values = [float(dist[i]) for i in center_idx if valid[i] == 1]
    edge_values = [float(dist[i]) for i in edge_idx if valid[i] == 1]

    center_mean = _safe_mean(center_values)
    edge_mean = _safe_mean(edge_values)
    if center_mean < 0 or edge_mean < 0:
        diff = -1.0
    else:
        diff = center_mean - edge_mean

    return center_mean, edge_mean, diff


def _roughness(dist: list[int], valid: list[int], side: int) -> float:
    if side == 0:
        return -1.0

    diffs: list[float] = []
    for r in range(side):
        for c in range(side):
            idx = r * side + c
            if valid[idx] != 1:
                continue

            if c + 1 < side:
                right = idx + 1
                if valid[right] == 1:
                    diffs.append(abs(float(dist[idx]) - float(dist[right])))
            if r + 1 < side:
                down = idx + side
                if valid[down] == 1:
                    diffs.append(abs(float(dist[idx]) - float(dist[down])))

    return _safe_mean(diffs)


def _filter_valid_distances(distance_mm: list[int], valid: list[int], min_mm: int, max_mm: int) -> list[float]:
    out: list[float] = []
    for d, v in zip(distance_mm, valid):
        if v != 1:
            continue
        if d < min_mm or d > max_mm:
            continue
        out.append(float(d))
    return out


def _window_feature(window: Iterable[float]) -> tuple[float, float]:
    values = [v for v in window if v >= 0.0]
    if not values:
        return -1.0, -1.0
    avg = fmean(values)
    return avg, _std(values, avg)


def extract_features(frame: dict, min_mm: int, max_mm: int) -> dict:
    frame_id = int(frame.get("frame_id", -1))
    mcu_ts_ms = int(frame.get("mcu_ts_ms", -1))
    host_ts_ns = int(frame.get("host_ts_ns", -1))
    resolution = int(frame.get("resolution", 0))
    fps = int(frame.get("fps", -1))

    distance_mm = [int(x) for x in frame.get("distance_mm", [])]
    valid = [int(x) for x in frame.get("valid", [])]
    signal = [float(x) for x in frame.get("signal_per_spad", [])]
    ambient = [float(x) for x in frame.get("ambient_per_spad", [])]

    if resolution <= 0:
        resolution = len(distance_mm)

    if len(valid) != len(distance_mm):
        valid = [1] * len(distance_mm)

    valid_count = sum(1 for v in valid if v == 1)
    total_count = len(valid)
    valid_ratio = (valid_count / total_count) if total_count else 0.0

    valid_dist = _filter_valid_distances(distance_mm, valid, min_mm, max_mm)
    sorted_dist = sorted(valid_dist)

    dist_mean = _safe_mean(valid_dist)
    dist_std = _std(valid_dist, dist_mean) if dist_mean >= 0 else -1.0
    dist_min = min(valid_dist) if valid_dist else -1.0
    dist_max = max(valid_dist) if valid_dist else -1.0
    dist_p10 = _percentile(sorted_dist, 10.0)
    dist_p50 = _percentile(sorted_dist, 50.0)
    dist_p90 = _percentile(sorted_dist, 90.0)

    near_100 = sum(1 for d in valid_dist if d <= 100.0)
    near_200 = sum(1 for d in valid_dist if d <= 200.0)
    near_300 = sum(1 for d in valid_dist if d <= 300.0)
    denom = float(len(valid_dist)) if valid_dist else 1.0

    side = _as_square_side(resolution)
    center_mean, edge_mean, center_edge_diff = _center_edge_stats(distance_mm, valid, side)
    roughness = _roughness(distance_mm, valid, side)

    avg_signal = _safe_mean(signal)
    avg_ambient = _safe_mean(ambient)

    return {
        "frame_id": frame_id,
        "mcu_ts_ms": mcu_ts_ms,
        "host_ts_ns": host_ts_ns,
        "fps": fps,
        "resolution": resolution,
        "valid_count": valid_count,
        "total_count": total_count,
        "valid_ratio": valid_ratio,
        "dist_min_mm": dist_min,
        "dist_max_mm": dist_max,
        "dist_mean_mm": dist_mean,
        "dist_std_mm": dist_std,
        "dist_p10_mm": dist_p10,
        "dist_p50_mm": dist_p50,
        "dist_p90_mm": dist_p90,
        "near_ratio_100mm": near_100 / denom,
        "near_ratio_200mm": near_200 / denom,
        "near_ratio_300mm": near_300 / denom,
        "center_mean_mm": center_mean,
        "edge_mean_mm": edge_mean,
        "center_edge_diff_mm": center_edge_diff,
        "roughness_mm": roughness,
        "avg_signal": avg_signal,
        "avg_ambient": avg_ambient,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--in", dest="input_path", required=True, help="Input TOF jsonl from receiver")
    parser.add_argument("--out", dest="output_path", required=True, help="Output feature jsonl")
    parser.add_argument("--window-size", type=int, default=15, help="Sliding window frame count, default 15")
    parser.add_argument("--min-mm", type=int, default=20, help="Minimum valid distance for feature extraction")
    parser.add_argument("--max-mm", type=int, default=2000, help="Maximum valid distance for feature extraction")
    parser.add_argument("--label", default="", help="Optional label attached to every output row")
    args = parser.parse_args()

    input_path = Path(args.input_path)
    output_path = Path(args.output_path)

    if not input_path.exists():
        raise SystemExit(
            f"Input file not found: {input_path}. "
            f"Please collect TOF frames first with tof_usart6_receiver.py"
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)

    win_valid_ratio: deque[float] = deque(maxlen=args.window_size)
    win_dist_mean: deque[float] = deque(maxlen=args.window_size)
    win_roughness: deque[float] = deque(maxlen=args.window_size)

    total = 0
    kept = 0

    with input_path.open("r", encoding="utf-8") as rf, output_path.open("w", encoding="utf-8") as wf:
        for line in rf:
            total += 1
            text = line.strip()
            if not text:
                continue

            try:
                obj = json.loads(text)
            except json.JSONDecodeError:
                continue

            frame = obj.get("frame")
            if not isinstance(frame, dict):
                continue

            feat = extract_features(frame, args.min_mm, args.max_mm)

            win_valid_ratio.append(feat["valid_ratio"])
            win_dist_mean.append(feat["dist_mean_mm"])
            win_roughness.append(feat["roughness_mm"])

            valid_ratio_mean_w, valid_ratio_std_w = _window_feature(win_valid_ratio)
            dist_mean_mean_w, dist_mean_std_w = _window_feature(win_dist_mean)
            rough_mean_w, rough_std_w = _window_feature(win_roughness)

            feat["w_valid_ratio_mean"] = valid_ratio_mean_w
            feat["w_valid_ratio_std"] = valid_ratio_std_w
            feat["w_dist_mean_mm_mean"] = dist_mean_mean_w
            feat["w_dist_mean_mm_std"] = dist_mean_std_w
            feat["w_roughness_mm_mean"] = rough_mean_w
            feat["w_roughness_mm_std"] = rough_std_w

            if args.label:
                feat["label"] = args.label

            wf.write(json.dumps(feat, ensure_ascii=True) + "\n")
            kept += 1

    print(f"Done. input_lines={total} output_rows={kept} out={output_path}")


if __name__ == "__main__":
    main()
